account: epic
app: ATML
atm_io_layout_x: 1
atm_io_layout_y: 1
atm_layout_x: 2
atm_layout_y: 4
coldstart: 'YES'
coupler_calendar: 3
date_cycle_freq_hr: 24
date_first_cycle: 2022122100
date_last_cycle: 2022122200
dt_atmos: 720
dt_runseq: 720
envir: test_atml_cold
exp_case_name: atml_coldstart_00
fcsthr: 24
fhrot: 0
ic_data_model: GFS
imo: 384
jmo: 190
lnd_calc_snet: .false.
lnd_ic_type: sfc
lnd_initial_albedo: 0.2
lnd_layout_x: 1
lnd_layout_y: 2
lnd_output_freq_sec: 21600
med_coupling_mode: ufs.frac
model_ver: v2.1.0
net: landda
nprocs_analysis: 6
nprocs_fcst_ic: 36
output_fh: '6 -1'
res: 96
restart_interval: '6 -1'
run: landda
we2e_test: 'NO'
write_groups: 1
write_tasks_per_group: 6
