ACCOUNT: epic
APP: LND
COLDSTART: 'YES'
COUPLER_CALENDAR: 2
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2000010300
DATE_LAST_CYCLE: 2000010400
DT_ATMOS: 900
DT_RUNSEQ: 3600
envir: test_lnd_cold
EXP_CASE_NAME: lnd_coldstart_00
FCSTHR: 24
JEDI_ALGORITHM: letkf
LND_CALC_SNET: .true.
LND_IC_TYPE: custom
LND_INITIAL_ALBEDO: 0.25
LND_LAYOUT_X: 1
LND_LAYOUT_Y: 2
LND_OUTPUT_FREQ_SEC: 21600
MED_COUPLING_MODE: ufs.nfrac.aoflux
model_ver: v2.1.0
net: landda
NPROCS_ANALYSIS: 6
NPZ: 127
RES: 96
RUN: landda
WE2E_TEST: 'NO'
