ACCOUNT: epic
APP: ATML
ATM_IO_LAYOUT_X: 1
ATM_IO_LAYOUT_Y: 1
ATM_LAYOUT_X: 2
ATM_LAYOUT_Y: 4
COLDSTART: 'YES'
COUPLER_CALENDAR: 3
DATE_CYCLE_FREQ_HR: 24
DATE_FIRST_CYCLE: 2021122100
DATE_LAST_CYCLE: 2021122200
DT_ATMOS: 720
DT_RUNSEQ: 720
envir: test_atml_cold
EXP_CASE_NAME: atml_coldstart_00
FCSTHR: 24
FHROT: 0
IC_DATA_MODEL: GFS
IMO: 384
JEDI_ALGORITHM: letkf
JMO: 190
LND_CALC_SNET: .false.
LND_IC_TYPE: sfc
LND_INITIAL_ALBEDO: 0.2
LND_LAYOUT_X: 1
LND_LAYOUT_Y: 2
LND_OUTPUT_FREQ_SEC: 21600
MED_COUPLING_MODE: ufs.frac
model_ver: v2.1.0
net: landda
NPROCS_ANALYSIS: 6
NPROCS_FCST_IC: 36
NPZ: 127
OUTPUT_FH: '6 -1'
RES: 96
RESTART_INTERVAL: '6 -1'
RUN: landda
WE2E_TEST: 'NO'
WRITE_GROUPS: 1
WRITE_TASKS_PER_GROUP: 6

